"""
Dev-time tool: build the `wholesale` domain's analysis-ready CSVs.

Unlike the other domains, the Northgate Retail Group source repo does not ship
CSVs — its warehouse is a partitioned parquet dataset of ~539k order lines under
`wholesale-analytics-platform/cache/` (regenerated by `seed.generate_synthetic_data`,
and gitignored there). Vendoring half a million rows into a repo that commits its
data would be silly, so this script pre-aggregates the fact into a handful of
small, analysis-ready tables and writes them twice:

  * into the source repo's cache (so `source` in data_manifest.py resolves and
    scripts/vendor_data.py can re-copy them), and
  * straight into ask-your-data/data/wholesale/ (what the app actually reads).

Revenue and cost follow the warehouse's own definitions, not a re-derivation:

    revenue = pack_weight_lb_sum * Price      when UnitOfBillingId = 3 (scale item)
              pack_item_count_sum * Price     otherwise (each item)
    cogs    = the same expression against CostPrice

Legacy source-system column names are translated on the way out
(ProteinType -> department, YieldPct -> sell_through_pct); the source `Province`
column is dropped, because it holds one representative state per region rather than
the city's own state.

    python scripts/build_wholesale_extract.py --portfolio-root ..
"""

import argparse
from pathlib import Path

import duckdb

ROOT = Path(__file__).resolve().parent.parent

REVENUE = ("CASE WHEN UnitOfBillingId = 3 THEN pack_weight_lb_sum * Price "
           "ELSE pack_item_count_sum * Price END")
COGS = ("CASE WHEN UnitOfBillingId = 3 THEN pack_weight_lb_sum * CostPrice "
        "ELSE pack_item_count_sum * CostPrice END")

# Fiscal year starts in October, matching cache/finance.
FY = "CASE WHEN month(Date) >= 10 THEN year(Date) + 1 ELSE year(Date) END"
FP = "((month(Date) - 10) % 12) + 1"


def queries(fact: str, finance: str, marketing: str, labor: str) -> dict[str, str]:
    return {
        # ---- monthly fact, department x region
        "fact_department_month": f"""
            SELECT
                CAST(date_trunc('month', Date) AS DATE)      AS month,
                strftime(Date, '%b %Y')                      AS month_label,
                {FY}                                         AS fiscal_year,
                {FP}                                         AS fiscal_period,
                ProteinType                                  AS department,
                RegionName                                   AS region,
                ROUND(SUM({REVENUE}), 2)                     AS revenue,
                ROUND(SUM({COGS}), 2)                        AS cogs,
                ROUND(SUM({REVENUE}) - SUM({COGS}), 2)       AS gross_margin,
                ROUND(SUM(GrossSales), 2)                    AS gross_sales,
                ROUND(SUM(DiscountAmount), 2)                AS discount_amount,
                ROUND(SUM(QuantityOrdered), 2)               AS cases_ordered,
                ROUND(SUM(QuantityShipped), 2)               AS cases_shipped,
                ROUND(SUM(ShippedLb), 2)                     AS pounds_shipped,
                COUNT(*)                                     AS order_lines,
                COUNT(*) FILTER (WHERE NOT IsLate)           AS on_time_lines,
                COUNT(*) FILTER (WHERE IsLate)               AS late_lines,
                COUNT(*) FILTER (WHERE IsShortShip)          AS short_ship_lines,
                COUNT(*) FILTER (WHERE IsStockout)           AS stockout_lines,
                COUNT(DISTINCT CustomerId)                   AS stores_selling
            FROM {fact}
            GROUP BY 1,2,3,4,5,6
            ORDER BY 1,5,6
        """,
        # ---- monthly fact, store format
        "fact_segment_month": f"""
            SELECT
                CAST(date_trunc('month', Date) AS DATE)      AS month,
                strftime(Date, '%b %Y')                      AS month_label,
                {FY}                                         AS fiscal_year,
                {FP}                                         AS fiscal_period,
                CustomerSegment                              AS store_format,
                ANY_VALUE(IsRetail)                          AS is_physical_store,
                COUNT(DISTINCT OrderId)                      AS orders,
                COUNT(*)                                     AS order_lines,
                COUNT(DISTINCT CustomerId)                   AS active_stores,
                ROUND(SUM({REVENUE}), 2)                     AS revenue,
                ROUND(SUM({COGS}), 2)                        AS cogs,
                ROUND(SUM({REVENUE}) - SUM({COGS}), 2)       AS gross_margin,
                ROUND(SUM(DiscountAmount), 2)                AS discount_amount,
                ROUND(SUM(QuantityOrdered), 2)               AS cases_ordered,
                ROUND(SUM(QuantityShipped), 2)               AS cases_shipped,
                ROUND(SUM(BackorderQty), 2)                  AS backorder_cases,
                COUNT(*) FILTER (WHERE NOT IsLate)           AS on_time_lines,
                COUNT(*) FILTER (WHERE IsLate)               AS late_lines
            FROM {fact}
            GROUP BY 1,2,3,4,5
            ORDER BY 1,5
        """,
        # ---- store dimension + lifetime rollup
        "dim_store": f"""
            SELECT
                CustomerId                                   AS store_id,
                ANY_VALUE(CustomerName)                      AS store_name,
                ANY_VALUE(CustomerSegment)                   AS store_format,
                ANY_VALUE(IsRetail)                          AS is_physical_store,
                ANY_VALUE(City)                              AS city,
                ANY_VALUE(RegionName)                        AS region,
                ANY_VALUE(SalesRepId)                        AS sales_rep_id,
                ANY_VALUE(SalesRepName)                      AS sales_rep_name,
                CAST(MIN(Date) AS DATE)                      AS first_order_date,
                CAST(MAX(Date) AS DATE)                      AS last_order_date,
                COUNT(DISTINCT OrderId)                      AS orders,
                COUNT(*)                                     AS order_lines,
                ROUND(SUM({REVENUE}), 2)                     AS revenue,
                ROUND(SUM({COGS}), 2)                        AS cogs,
                ROUND(SUM({REVENUE}) - SUM({COGS}), 2)       AS gross_margin,
                ROUND(SUM(DiscountAmount), 2)                AS discount_amount,
                ROUND(SUM(QuantityOrdered), 2)               AS cases_ordered,
                ROUND(SUM(QuantityShipped), 2)               AS cases_shipped,
                ROUND(100.0 * COUNT(*) FILTER (WHERE NOT IsLate) / COUNT(*), 2) AS on_time_line_pct,
                ROUND(100.0 * SUM(QuantityShipped) / NULLIF(SUM(QuantityOrdered), 0), 2) AS fill_rate_pct
            FROM {fact}
            GROUP BY 1
            ORDER BY revenue DESC
        """,
        # ---- product / SKU dimension + lifetime rollup
        "dim_product": f"""
            SELECT
                ProductId                                    AS product_id,
                ANY_VALUE(SKU)                               AS sku,
                ANY_VALUE(ProductName)                       AS product_name,
                ANY_VALUE(ProteinType)                       AS department,
                ANY_VALUE(SupplierId)                        AS supplier_id,
                ANY_VALUE(SupplierName)                      AS supplier_name,
                ANY_VALUE(UnitOfBillingId)                   AS unit_of_billing_id,
                CASE WHEN ANY_VALUE(UnitOfBillingId) = 3 THEN 'weight' ELSE 'each' END AS billing_basis,
                ANY_VALUE(IsCatchWeight)                     AS is_scale_item,
                ROUND(100.0 * ANY_VALUE(YieldPct), 2)        AS sell_through_pct,
                ROUND(AVG(ListPrice), 4)                     AS avg_list_price,
                ROUND(AVG(Price), 4)                         AS avg_net_price,
                ROUND(AVG(CostPrice), 4)                     AS avg_unit_cost,
                COUNT(*)                                     AS order_lines,
                ROUND(SUM(QuantityShipped), 2)               AS cases_shipped,
                ROUND(SUM(ShippedLb), 2)                     AS pounds_shipped,
                ROUND(SUM({REVENUE}), 2)                     AS revenue,
                ROUND(SUM({COGS}), 2)                        AS cogs,
                ROUND(SUM({REVENUE}) - SUM({COGS}), 2)       AS gross_margin,
                ROUND(AVG(DaysOfSupply), 2)                  AS avg_days_of_supply,
                ROUND(AVG(OnHandQty), 2)                     AS avg_on_hand_cases,
                ROUND(AVG(ReorderPointQty), 2)               AS avg_reorder_point_cases,
                COUNT(*) FILTER (WHERE IsStockout)           AS stockout_lines
            FROM {fact}
            GROUP BY 1
            ORDER BY revenue DESC
        """,
        # ---- supplier / vendor dimension + lifetime rollup
        "dim_supplier": f"""
            SELECT
                SupplierId                                   AS supplier_id,
                ANY_VALUE(SupplierName)                      AS supplier_name,
                MODE(ProteinType)                            AS primary_department,
                COUNT(DISTINCT ProteinType)                  AS departments_supplied,
                COUNT(DISTINCT ProductId)                    AS skus_supplied,
                COUNT(DISTINCT CustomerId)                   AS stores_served,
                COUNT(*)                                     AS order_lines,
                ROUND(SUM(QuantityOrdered), 2)               AS cases_ordered,
                ROUND(SUM(QuantityShipped), 2)               AS cases_shipped,
                ROUND(SUM({REVENUE}), 2)                     AS revenue,
                ROUND(SUM({COGS}), 2)                        AS cogs,
                ROUND(SUM({REVENUE}) - SUM({COGS}), 2)       AS gross_margin,
                ROUND(100.0 * (SUM({REVENUE}) - SUM({COGS})) / NULLIF(SUM({REVENUE}), 0), 2) AS gross_margin_pct,
                ROUND(100.0 * COUNT(*) FILTER (WHERE NOT IsLate) / COUNT(*), 2) AS on_time_line_pct,
                ROUND(100.0 * SUM(QuantityShipped) / NULLIF(SUM(QuantityOrdered), 0), 2) AS fill_rate_pct,
                COUNT(*) FILTER (WHERE IsStockout)           AS stockout_lines,
                ROUND(AVG(TransitDays), 2)                   AS avg_transit_days
            FROM {fact}
            GROUP BY 1
            ORDER BY revenue DESC
        """,
        # ---- sales rep quota attainment by month
        "fact_rep_month": f"""
            SELECT
                CAST(date_trunc('month', Date) AS DATE)      AS month,
                strftime(Date, '%b %Y')                      AS month_label,
                {FY}                                         AS fiscal_year,
                {FP}                                         AS fiscal_period,
                SalesRepId                                   AS sales_rep_id,
                ANY_VALUE(SalesRepName)                      AS sales_rep_name,
                ROUND(MAX(MonthlyQuota), 2)                  AS monthly_quota,
                ROUND(SUM({REVENUE}), 2)                     AS revenue,
                ROUND(SUM({COGS}), 2)                        AS cogs,
                ROUND(SUM({REVENUE}) - SUM({COGS}), 2)       AS gross_margin,
                ROUND(100.0 * SUM({REVENUE}) / NULLIF(MAX(MonthlyQuota), 0), 2) AS quota_attainment_pct,
                COUNT(DISTINCT OrderId)                      AS orders,
                COUNT(DISTINCT CustomerId)                   AS active_stores,
                COUNT(*)                                     AS order_lines
            FROM {fact}
            GROUP BY 1,2,3,4,5
            ORDER BY 1,5
        """,
        # ---- monthly finance summary (already monthly at source)
        "finance_monthly": f"""
            SELECT
                CAST(month AS DATE) AS month, month_label, fiscal_year, fiscal_period, days_in_month,
                gross_sales, discounts, revenue, cogs, gross_profit, orders,
                operating_expenses, opex_selling, opex_warehouse, opex_occupancy,
                opex_admin, opex_technology, opex_marketing,
                depreciation_amortization, interest_expense, other_expense,
                pre_tax_income, tax_expense, net_income,
                cash, accounts_receivable, inventory, current_assets, net_ppe, total_assets,
                accounts_payable, ap_overdue, accrued_liabilities, current_liabilities,
                long_term_debt, total_liabilities, capex,
                ar_current, ar_d1_30, ar_d31_60, ar_d61_90, ar_d90_plus
            FROM {finance}
            ORDER BY month
        """,
        # ---- marketing campaigns (already monthly x campaign at source)
        "marketing_campaigns": f"""
            SELECT
                CAST(month AS DATE) AS month, month_label, fiscal_year, fiscal_period,
                campaign_id, campaign_name, channel_key, channel,
                spend, leads, qualified_leads, new_customers,
                selling_spend_month, acquisition_selling_spend_month, revenue_month
            FROM {marketing}
            ORDER BY month, channel_key
        """,
        # ---- labor: timeclock rows rolled up to function x month
        "labor_department_month": f"""
            SELECT
                labor_month                                  AS month_label,
                CAST(date_trunc('month', labor_date) AS DATE) AS month,
                department_name                              AS function_name,
                ANY_VALUE(department_number)                 AS function_number,
                COUNT(DISTINCT employee_code)                AS employees,
                COUNT(*)                                     AS timeclock_days,
                ROUND(SUM(scheduled_h), 2)                   AS scheduled_hours,
                ROUND(SUM(paid_hours), 2)                    AS paid_hours,
                ROUND(SUM(regular_h), 2)                     AS regular_hours,
                ROUND(SUM(overtime_h), 2)                    AS overtime_hours,
                ROUND(SUM(absence_h), 2)                     AS absence_hours,
                ROUND(SUM(labor_cost), 2)                    AS labor_cost,
                ROUND(SUM(overtime_cost), 2)                 AS overtime_cost,
                ROUND(100.0 * SUM(overtime_h) / NULLIF(SUM(paid_hours), 0), 2) AS overtime_hours_pct,
                ROUND(SUM(labor_cost) / NULLIF(SUM(paid_hours), 0), 2) AS cost_per_paid_hour,
                COUNT(DISTINCT employee_code) FILTER (WHERE separation_flag) AS separations
            FROM (
                SELECT *,
                    COALESCE(schedule_hours, 0)                                  AS scheduled_h,
                    CASE WHEN time_category = 'Regular'  THEN paid_hours ELSE 0 END AS regular_h,
                    CASE WHEN time_category = 'Overtime' THEN paid_hours ELSE 0 END AS overtime_h,
                    CASE WHEN time_category = 'Absence'  THEN paid_hours ELSE 0 END AS absence_h,
                    CASE WHEN time_category = 'Overtime' THEN labor_cost ELSE 0 END AS overtime_cost
                FROM {labor}
            )
            GROUP BY 1,2,3
            ORDER BY 2,3
        """,
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--portfolio-root", default=str(ROOT.parent))
    args = ap.parse_args()
    src_root = Path(args.portfolio_root).resolve()
    repo = src_root / "wholesale-analytics-platform"

    fact = f"read_parquet('{(repo / 'cache/fact_dataset/**/*.parquet').as_posix()}')"
    finance = f"read_parquet('{(repo / 'cache/finance/fact_dataset/finance_demo.parquet').as_posix()}')"
    marketing = f"read_parquet('{(repo / 'cache/marketing/fact_dataset/marketing_demo.parquet').as_posix()}')"
    labor = f"read_parquet('{(repo / 'cache/labor/fact_dataset/labor_demo.parquet').as_posix()}')"

    out_repo = repo / "cache" / "ask_your_data"
    out_data = ROOT / "data" / "wholesale"
    out_repo.mkdir(parents=True, exist_ok=True)
    out_data.mkdir(parents=True, exist_ok=True)

    con = duckdb.connect()
    for table, sql in queries(fact, finance, marketing, labor).items():
        for target in (out_repo, out_data):
            path = (target / f"{table}.csv").as_posix()
            con.execute(f"COPY ({sql}) TO '{path}' (HEADER, DELIMITER ',')")
        rows = con.execute(f"SELECT COUNT(*) FROM ({sql})").fetchone()[0]
        print(f"  {table:<26} {rows:>6} rows")
    con.close()


if __name__ == "__main__":
    main()
